String.toLocaleString({

	"it": {
    "%game-intro"           : "Join tiles and eat <strong>GREASE!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>combine!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"https://wjgitter.github.io/2048-drive-thru/\">2048-drive-thru</a> is a spin-off by William of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"https://web.archive.org/web/20140320011555/https://gabrielecirulli.com/\" target=\"_blank\">Gabriele Cirulli.</a>",
    "%credits"              : "Food images by Freepik - Flaticon. See readme for image attribution.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-drive-thru #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'french fries',
    '%4'                    : 'chicken nuggets',
    '%8'                    : 'chicken tenders',
    '%16'                   : 'corn dog',
    '%32'                   : 'hot dog',
    '%64'                   : 'cheeseburger',
    '%128'                  : 'double burger',
    '%256'                  : 'soda',
    '%512'                  : 'slush',
    '%1024'                 : 'pizza slice',
    '%2048'                 : 'pizza',
    '%4096'                 : 'sundae',
    '%8192'                 : 'banana split',
    '%p0'                   : 'french fries',
    '%p4'                   : 'chicken nuggets',
    '%p8'                   : 'chicken tenders',
    '%p16'                  : 'corn dog',
    '%p32'                  : 'hot dog',
    '%p64'                  : 'cheeseburger',
    '%p128'                 : 'double burger',
    '%p256'                 : 'soda',
    '%p512'                 : 'slush',
    '%p1024'                : 'pizza slice',
    '%p2048'                : 'pizza',
    '%p4096'                : 'sundae',
    '%p8192'                : 'banana split'

	},

  "en": {
    "%game-intro"           : "Join tiles and eat <strong>GREASE!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>combine!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"https://wjgitter.github.io/2048-drive-thru/\">2048-drive-thru</a> is a spin-off by William of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"https://web.archive.org/web/20140320011555/https://gabrielecirulli.com/\" target=\"_blank\">Gabriele Cirulli.</a>",
    "%credits"              : "Food images by Freepik - Flaticon. See readme for image attribution.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-drive-thru #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'french fries',
    '%4'                    : 'chicken nuggets',
    '%8'                    : 'chicken tenders',
    '%16'                   : 'corn dog',
    '%32'                   : 'hot dog',
    '%64'                   : 'cheeseburger',
    '%128'                  : 'double burger',
    '%256'                  : 'soda',
    '%512'                  : 'slush',
    '%1024'                 : 'pizza slice',
    '%2048'                 : 'pizza',
    '%4096'                 : 'sundae',
    '%8192'                 : 'banana split',
    '%p0'                   : 'french fries',
    '%p4'                   : 'chicken nuggets',
    '%p8'                   : 'chicken tenders',
    '%p16'                  : 'corn dog',
    '%p32'                  : 'hot dog',
    '%p64'                  : 'cheeseburger',
    '%p128'                 : 'double burger',
    '%p256'                 : 'soda',
    '%p512'                 : 'slush',
    '%p1024'                : 'pizza slice',
    '%p2048'                : 'pizza',
    '%p4096'                : 'sundae',
    '%p8192'                : 'banana split'
  }

});
